// <auto-generated />
using System;
using Infrastructure.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20260601125251_AddCourseEnrollmentsAndLecturerCourses")]
    partial class AddCourseEnrollmentsAndLecturerCourses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CoreApp.Domain.Entities.AcademicYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AcademicYears");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3bb4d12d-a507-46db-b676-f8d25d73cf59"),
                            Name = "2024/2025"
                        },
                        new
                        {
                            Id = new Guid("8e7a123e-b9b1-42d5-8bdd-c3cd7d7e96fb"),
                            Name = "2025/2026"
                        });
                });

            modelBuilder.Entity("CoreApp.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EctsCredits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e8f8f66-bb84-4f77-8a42-6052b8c64410"),
                            Code = "ALG101",
                            CompletionType = "Exam",
                            EctsCredits = 6,
                            Name = "Algorytmy i struktury danych",
                            Semester = "Winter"
                        },
                        new
                        {
                            Id = new Guid("1bcf84f4-57fa-4fb1-a655-bd8ee4d061d2"),
                            Code = "DBS201",
                            CompletionType = "CreditWithGrade",
                            EctsCredits = 5,
                            Name = "Bazy danych",
                            Semester = "Summer"
                        });
                });

            modelBuilder.Entity("CoreApp.Domain.Entities.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InstructorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentRefId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StudentRefId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f063f470-e91d-447a-96ae-132286d4ca77"),
                            AcademicYearId = new Guid("8e7a123e-b9b1-42d5-8bdd-c3cd7d7e96fb"),
                            CourseId = new Guid("8e8f8f66-bb84-4f77-8a42-6052b8c64410"),
                            Date = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            GradeType = "Partial",
                            GradeValue = "Grade40",
                            InstructorId = new Guid("0d7c4923-0ed0-4db9-a392-4b3c520ef77e"),
                            StudentRefId = new Guid("3d54091d-abc8-49ec-9590-93ad3ed5458f")
                        });
                });

            modelBuilder.Entity("CoreApp.Domain.Entities.GradeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedByUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewValue")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OldValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("GradeHistories");
                });

            modelBuilder.Entity("CoreApp.Domain.Entities.Lecturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d7c4923-0ed0-4db9-a392-4b3c520ef77e"),
                            Email = "jan.nowak@wsei.edu.pl",
                            Faculty = "Informatyka",
                            FirstName = "Jan",
                            LastName = "Nowak",
                            NationalId = "75010112346",
                            Title = "dr inż."
                        },
                        new
                        {
                            Id = new Guid("05f64714-3ac1-4327-8e02-fd519844126f"),
                            Email = "anna.kowalska@wsei.edu.pl",
                            Faculty = "Matematyka",
                            FirstName = "Anna",
                            LastName = "Kowalska",
                            NationalId = "78020254325",
                            Title = "mgr"
                        });
                });

            modelBuilder.Entity("CoreApp.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d54091d-abc8-49ec-9590-93ad3ed5458f"),
                            Email = "adam.nowak@example.com",
                            FirstName = "Adam",
                            LastName = "Nowak",
                            NationalId = "99010112342",
                            ProgramName = "Informatyka",
                            Status = "Active",
                            StudentId = "S001",
                            YearOfStudy = 1
                        },
                        new
                        {
                            Id = new Guid("7ba19ea5-3967-4b24-bb87-b14c9ee14770"),
                            Email = "ewa.kowalska@example.com",
                            FirstName = "Ewa",
                            LastName = "Kowalska",
                            NationalId = "98020254323",
                            ProgramName = "Matematyka",
                            Status = "OnLeave",
                            StudentId = "S002",
                            YearOfStudy = 2
                        });
                });

            modelBuilder.Entity("CourseEnrollment", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseEnrollments", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("8e8f8f66-bb84-4f77-8a42-6052b8c64410"),
                            StudentId = new Guid("3d54091d-abc8-49ec-9590-93ad3ed5458f")
                        },
                        new
                        {
                            CourseId = new Guid("1bcf84f4-57fa-4fb1-a655-bd8ee4d061d2"),
                            StudentId = new Guid("3d54091d-abc8-49ec-9590-93ad3ed5458f")
                        },
                        new
                        {
                            CourseId = new Guid("1bcf84f4-57fa-4fb1-a655-bd8ee4d061d2"),
                            StudentId = new Guid("7ba19ea5-3967-4b24-bb87-b14c9ee14770")
                        });
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.Entities.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7e79ebd0-aaaf-4888-bc21-3404b1a1818d",
                            ConcurrencyStamp = "9aae6557-4608-422c-8081-20c1d7703e04",
                            Description = "System administrator",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "f4f4fbb7-8ef2-47fe-8558-79206ad2fbd8",
                            ConcurrencyStamp = "4aef5cef-5339-4e20-a3df-4de38cd4af9f",
                            Description = "Dean office staff member",
                            Name = "DeanOfficeStaff",
                            NormalizedName = "DEANOFFICESTAFF"
                        },
                        new
                        {
                            Id = "73480eab-37e1-4f7f-ac39-b9e63313ace9",
                            ConcurrencyStamp = "1b0820de-73cd-46a6-9381-d95a02ab5be0",
                            Description = "University lecturer",
                            Name = "Lecturer",
                            NormalizedName = "LECTURER"
                        },
                        new
                        {
                            Id = "97d1d11b-76cc-4320-8bf3-ee52ca1cf0d7",
                            ConcurrencyStamp = "2aedf543-0be5-4d99-b269-5fa77a62c6f6",
                            Description = "University student",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0f73f8f9-0800-40dd-bf77-540069454fe8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "41193c7e-72d9-44c8-b553-c00d3fb7a1df",
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Dean Office",
                            Email = "admin@wsei.edu.pl",
                            EmailConfirmed = true,
                            FirstName = "Anna",
                            FullName = "Anna Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@WSEI.EDU.PL",
                            NormalizedUserName = "ADMIN@WSEI.EDU.PL",
                            PasswordHash = "AQAAAAIAAYagAAAAEA0RjJEUakY8kIZ+ldE1OU8lyvxba4g4XTpisBuOdVceGP2hn/UqwTkQtDcdDyuEgw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c7595157-b163-429e-a80e-3a914904f2b2",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "admin@wsei.edu.pl"
                        },
                        new
                        {
                            Id = "ef444766-304f-4f77-bf64-baf2b23974ae",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d4febf57-6ea9-4130-8740-32945d585b1d",
                            CreatedAt = new DateTime(2026, 1, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Students",
                            Email = "adam.nowak@wsei.edu.pl",
                            EmailConfirmed = true,
                            FirstName = "Adam",
                            FullName = "Adam Nowak",
                            LastName = "Nowak",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADAM.NOWAK@WSEI.EDU.PL",
                            NormalizedUserName = "ADAM.NOWAK@WSEI.EDU.PL",
                            PasswordHash = "AQAAAAIAAYagAAAAEKEsVWWEm2JWiwk1zHO7Vv84hmXhLrP2mRJEA0VIqqT+d8ENvH0Ojj5MaWINX8J76g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e85bb4bf-37c5-4964-a85e-0a37b7b828ad",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "adam.nowak@wsei.edu.pl"
                        });
                });

            modelBuilder.Entity("Infrastructure.Security.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("LecturerCourse", b =>
                {
                    b.Property<Guid>("LecturerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.HasKey("LecturerId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("LecturerCourses", (string)null);

                    b.HasData(
                        new
                        {
                            LecturerId = new Guid("0d7c4923-0ed0-4db9-a392-4b3c520ef77e"),
                            CourseId = new Guid("8e8f8f66-bb84-4f77-8a42-6052b8c64410")
                        },
                        new
                        {
                            LecturerId = new Guid("05f64714-3ac1-4327-8e02-fd519844126f"),
                            CourseId = new Guid("1bcf84f4-57fa-4fb1-a655-bd8ee4d061d2")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "0f73f8f9-0800-40dd-bf77-540069454fe8",
                            RoleId = "7e79ebd0-aaaf-4888-bc21-3404b1a1818d"
                        },
                        new
                        {
                            UserId = "0f73f8f9-0800-40dd-bf77-540069454fe8",
                            RoleId = "f4f4fbb7-8ef2-47fe-8558-79206ad2fbd8"
                        },
                        new
                        {
                            UserId = "ef444766-304f-4f77-bf64-baf2b23974ae",
                            RoleId = "97d1d11b-76cc-4320-8bf3-ee52ca1cf0d7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CoreApp.Domain.Entities.Grade", b =>
                {
                    b.HasOne("CoreApp.Domain.Entities.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreApp.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreApp.Domain.Entities.Lecturer", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CoreApp.Domain.Entities.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CoreApp.Domain.Entities.GradeHistory", b =>
                {
                    b.HasOne("CoreApp.Domain.Entities.Grade", "Grade")
                        .WithMany("History")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("CourseEnrollment", b =>
                {
                    b.HasOne("CoreApp.Domain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreApp.Domain.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LecturerCourse", b =>
                {
                    b.HasOne("CoreApp.Domain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreApp.Domain.Entities.Lecturer", null)
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.EntityFramework.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoreApp.Domain.Entities.Grade", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("CoreApp.Domain.Entities.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
