@WebApi_HostAddress = http://localhost:5148
@Student_GUID = 3d54091d-abc8-49ec-9590-93ad3ed5458f
@Course_GUID = 8e8f8f66-bb84-4f77-8a42-6052b8c64410
@Lecturer_GUID = 0d7c4923-0ed0-4db9-a392-4b3c520ef77e
@AcademicYear_GUID = 8e7a123e-b9b1-42d5-8bdd-c3cd7d7e96fb

GET {{WebApi_HostAddress}}/api/students
Accept: application/json

###
GET {{WebApi_HostAddress}}/api/students/{{Student_GUID}}
Accept: application/json

###
POST {{WebApi_HostAddress}}/api/students
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Nowak",
  "nationalId": "99010112345",
  "email": "adam@wsei.edu.pl",
  "studentId": "S100",
  "programName": "Informatyka",
  "yearOfStudy": 2,
  "status": 0
}

###
PUT {{WebApi_HostAddress}}/api/students/{{Student_GUID}}
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Nowak-Zmieniony",
  "nationalId": "99010112345",
  "email": "adam.nowy@wsei.edu.pl",
  "studentId": "S100",
  "programName": "Informatyka",
  "yearOfStudy": 3,
  "status": 0
}

###
POST {{WebApi_HostAddress}}/api/students/{{Student_GUID}}/grades
Content-Type: application/json

{
  "courseId": "{{Course_GUID}}",
  "lecturerId": "{{Lecturer_GUID}}",
  "academicYearId": "{{AcademicYear_GUID}}",
  "date": "2026-05-09T00:00:00Z",
  "gradeType": 1,
  "gradeValue": 4.5
}

###
GET {{WebApi_HostAddress}}/api/students/{{Student_GUID}}/grades
Accept: application/json

###
PUT {{WebApi_HostAddress}}/api/students/{{Student_GUID}}/grades/<grade-guid>
Content-Type: application/json

{
  "date": "2026-05-10T00:00:00Z",
  "gradeType": 2,
  "gradeValue": 5.0
}

###
POST {{WebApi_HostAddress}}/api/students/00000000-0000-0000-0000-000000000000/grades
Content-Type: application/json

{
  "courseId": "{{Course_GUID}}",
  "lecturerId": "{{Lecturer_GUID}}",
  "academicYearId": "{{AcademicYear_GUID}}",
  "date": "2026-05-09T00:00:00Z",
  "gradeType": 0,
  "gradeValue": 4.0
}
